# Generated by Django 6.1 on 2026-10-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อโซนจัดส่ง')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ค่าจัดส่ง (บาท)')),
                ('color', models.CharField(default='#3b82f6', max_length=50, verbose_name='สีพื้นที่ (Hex Code)')),
                ('polygon_data', models.JSONField(help_text='เก็บข้อมูล GeoJSON หรืออาเรย์พิกัด', verbose_name='ข้อมูลพิกัด (Polygon)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สโคปพื้นที่จัดส่ง',
                'verbose_name_plural': 'สโคปพื้นที่จัดส่ง',
            },
        ),
    ]
