"""
Django settings for KhaiKhao project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ดึงค่า SECRET_KEY จาก Environment Variables (ถ้าไม่มีจะใช้ค่าเริ่มต้นสำหรับทดสอบ)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-*7v=$4j2smtjtsm&g&l2xx-hzh2yjemi5b%00cpkk3sz#t!f6c')

# SECURITY WARNING: don't run with debug turned on in production!
# แนะนำให้ตั้งเป็น False เมื่ออัพขึ้น PythonAnywhere (ผ่าน Environment Variables)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# เพิ่มโดเมนของ PythonAnywhere และค่าพื้นฐานสำหรับรันในเครื่อง
ALLOWED_HOSTS = ['danaith64.pythonanywhere.com', '127.0.0.1', 'localhost']
# ALLOWED_HOSTS = ['f763-49-229-22-76.ngrok-free.app', '127.0.0.1', 'localhost']

# ==========================================
# ตั้งค่าความปลอดภัยสำหรับ PythonAnywhere (บังคับ HTTPS และแก้ปัญหาฟอร์ม)
# ==========================================
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = ['https://danaith64.pythonanywhere.com']

if not DEBUG:
    # บังคับให้เปลี่ยน HTTP เป็น HTTPS เสมอเมื่อรันบน Production (แก้ปัญหาแผนที่มือถือไม่แสดงพิกัด)
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Accounts',
    'Products',
    'Pos',
    'Expenses',
    'Reports',
    'Taxes',
    'History',
    'Stocks',
    'Riders',
    'ShopHistory',
    'Heatmap',
    'BackOffice',
    'DeliveryZones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KhaiKhao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KhaiKhao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# ตั้งเวลาเป็น UTC -7 (เช่น อเมริกา/เดนเวอร์)
TIME_ZONE = 'America/Denver'

USE_I18N = True
USE_TZ = True


# ==========================================
# ตั้งค่า Static Files & Media สำหรับ PythonAnywhere
# ==========================================

# Static files (CSS, JavaScript, Images ที่มากับธีมเว็บ)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# เป้าหมายของคำสั่ง collectstatic เพื่อให้ PythonAnywhere ดึงไปแสดงผล
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (รูปภาพที่ผู้ใช้อัปโหลด เช่น รูปสินค้า สลิปโอนเงิน)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==========================================

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'Accounts.User'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000
