# Generated by Django 6.1 on 2026-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='รายการรายจ่าย')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนเงิน')),
                ('expense_date', models.DateField(verbose_name='วันที่รายจ่าย')),
                ('category', models.CharField(choices=[('ingredient', 'วัตถุดิบ'), ('electricity', 'ค่าไฟ'), ('water', 'ค่าน้ำ'), ('rent', 'ค่าเช่า'), ('transport', 'ค่าเดินทาง'), ('equipment', 'อุปกรณ์'), ('salary', 'เงินเดือน / ค่าแรง'), ('maintenance', 'ค่าซ่อมบำรุง'), ('other', 'อื่น ๆ')], max_length=30, verbose_name='หมวดหมู่')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'รายจ่าย',
                'verbose_name_plural': 'รายจ่าย',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
