# Generated by Django 6.1 on 2026-08-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0003_expense_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='จ่ายแล้ว'),
        ),
    ]
