# Generated by Django 6.1 on 2026-09-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taxrecord',
            table='taxs_taxrecord',
        ),
    ]
