# Generated by Django 6.1 on 2026-08-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ชื่อบัญชี (เจ้าของบัญชี)'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่บัญชีธนาคาร'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อธนาคาร'),
        ),
        migrations.AddField(
            model_name='user',
            name='promptpay_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='หมายเลขพร้อมเพย์ (เบอร์โทร / เลขผู้เสียภาษี)'),
        ),
    ]
