# Generated by Django 6.1 on 2026-08-27 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(verbose_name='ปีภาษี (พ.ศ./ค.ศ.)')),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='รายได้ทั้งปี')),
                ('total_expenses_deduction', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ค่าใช้จ่ายและค่าลดหย่อน')),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='เงินได้สุทธิ')),
                ('tax_to_pay', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ภาษีที่ต้องชำระ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่บันทึก')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
        ),
    ]
