# Generated by Django 6.1 on 2026-09-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0002_deliverytask_dormitory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='dest_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='dest_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
