# Generated by Django 6.1 on 2026-09-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0003_deliverytask_dest_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliverytask',
            name='dest_latitude',
        ),
        migrations.RemoveField(
            model_name='deliverytask',
            name='dest_longitude',
        ),
        migrations.RemoveField(
            model_name='deliverytask',
            name='dormitory_name',
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Riders.dormitory'),
        ),
    ]
