# Generated by Django 6.1 on 2026-09-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0005_dormitory_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='zone',
            field=models.CharField(default='โซนหน้ามอ', max_length=50),
        ),
    ]
