# Generated by Django 6.1 on 2026-09-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0006_alter_dormitory_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='color',
            field=models.CharField(default='blue', max_length=30),
        ),
    ]
