# Generated by Django 6.1 on 2026-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riders', '0009_deliverytask_trip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='client_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
