# Generated by Django 6.1 on 2026-09-11 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาเปิดร้าน')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลาปิดร้าน')),
                ('is_open', models.BooleanField(default=True, verbose_name='สถานะ (เปิด/ปิด)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='พนักงาน/ร้านค้า')),
            ],
            options={
                'ordering': ['-open_time'],
            },
        ),
    ]
