# Generated by Django 6.1 on 2026-09-02 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อของใช้/วัตถุดิบ')),
                ('quantity', models.FloatField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('unit', models.CharField(max_length=50, verbose_name='หน่วยนับ (เช่น ใบ, กก., แพ็ค)')),
                ('alert_level', models.FloatField(default=0, verbose_name='แจ้งเตือนเมื่อต่ำกว่า')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IN', 'นำเข้า (+)'), ('OUT', 'เบิกออก (-)')], max_length=3)),
                ('amount', models.FloatField(verbose_name='จำนวนที่เข้า/ออก')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Stocks.stockitem')),
            ],
        ),
    ]
