# Generated by Django 4.2.11 on 2026-08-18 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสสินค้า')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาทุน')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาขาย')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='จำนวนคงเหลือ')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='จำนวนขั้นต่ำ')),
                ('unit', models.CharField(default='ชิ้น', max_length=50, verbose_name='หน่วย')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปสินค้า')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดขาย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Products.productcategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'db_table': 'products',
                'ordering': ['category', 'name'],
            },
        ),
    ]
