# Generated by Django 6.1 on 2026-09-26 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_created_by_productcategory_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='UNKNOWN', max_length=100, verbose_name='ประเภท Event')),
                ('payload', models.TextField(verbose_name='ข้อมูล JSON ที่รับมา')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่รับข้อมูล')),
            ],
        ),
    ]
